name: Build and start bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to QA Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -p 22 qa-team.ru >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -p 22 root@qa-team.ru << 'EOF'
            cd /root/dockers/remnawave-telegram-shop
            git pull
            docker compose up -d --build
          EOF
